#!/usr/bin/env python3

import subprocess
from sys import argv


def diff():
    return subprocess.check_output(
        ["git", "diff-index", "--cached", "HEAD"]
    ).splitlines()


def commit_size(commit_hash):
    if commit_hash == "0" * 40:
        # "Empty" hash to signal deletions (destination) or additions (source)
        return 0
    else:
        return int(subprocess.check_output(["git", "cat-file", "-s", commit_hash]))


def number_of_characters_changed(line):
    fields = line.decode("utf-8").split()

    before_commit = fields[2]
    after_commit = fields[3]

    return commit_size(after_commit) - commit_size(before_commit)


MAX_COMMIT_SIZE = int(argv[1]) if len(argv) >= 2 else 280

total_size = sum([number_of_characters_changed(line) for line in diff()])

if total_size > MAX_COMMIT_SIZE:
    print(
        "Total commit size (%d) exceeds +%d characters" % (total_size, MAX_COMMIT_SIZE)
    )
    exit(1)
